(function(f,k,m,l,e){f[k]=f[k]||{};for(f[k].q=f[k].q||[];e<l.length;)m(l[e++],f[k])})(window,"extole",function(f,k){k[f]=k[f]||function(){k.q.push([f,arguments])}},["log"],0);
extole.define||function(){function f(a){a=e(a);return x[a]}function k(a,b){extole.log("error","[REQUIRE] "+a,b)}function m(a,b){if(a.length)for(var p=0;p<a.length;p++)b(a[p],p);else for(p in a)Object.prototype.hasOwnProperty.call(a,p)&&b(a[p],p)}function l(a,b){var p=[];m(a,function(a,d){p[d]=b(a,d)});return p}function e(a){return"string"!==typeof a?a:/origin-\d/.test(a)?a.substring(a.indexOf("type=")).replace(/version=\d+:/,""):a}function n(a){var b=a.split("/").slice(-1)[0],p=b.length;m(b.toLowerCase(),
function(a){p+=" abcdefghijklmnopqrstuvwxyz1234567890-_.".indexOf(a)});return a.replace("origin","origin-"+p%8)}function h(a){var b=/^extole-creatives:/.test(a),d=/^extole-media:/.test(a),g=/^core-root:\/\//.test(a),c=/^extole-assets:/.test(a),p=/origin\./.test(a),r=/^http:/.test(a),e=/^https:/.test(a);return b?(a=a.slice(17),h("extole-assets:/core-modules/"+a)):c?(a=a.slice(14),h("extole-media:/assets/"+a)):d?(a=a.slice(13),a=extole.CORE_ROOT+a,h(a)):g?(a=a.slice(12),a=extole.CORE_ROOT+a,h(a)):p?
(a=n(a),a+="?site="+window.location.hostname,h(a)):r?(a=a.slice(5),h(a)):e?(a=a.slice(6),h(a)):a}function c(){}function b(){var a="undefined"!==typeof window.opera&&"[object Opera]"===window.opera.toString(),b=document.createElement("script");this.useInteractive=b.attachEvent&&!(b.attachEvent.toString&&0>b.attachEvent.toString().indexOf("[native code"))&&!a}function a(){m(x,function(a){a._fetched?a._defined||a.define():a.fetch()})}function g(a,b,d,g,r){if("$config"!=a){var p=f(a),q=p||new c;p||(p=
e(a),x[p]=q);a&&b&&(q._fetched=!0);q.start=q.start||(new Date).getTime();q.url=q.url||a;q.dependencies=q.dependencies||b;q.config=q.config||g;q.definedCallback=q.definedCallback||d;q.isRequire=q.isRequire||r}}function d(a,b,d,g){a instanceof Array&&(g=d,d=b,b=a,a=void 0);y.addDefine({url:a,dependencies:b,definedCallback:d,config:g})}function r(){u++;return"anonymous_"+u}var x={};c.prototype={getUnresolvedDependencies:function(){var a=[];m(this.dependencies,function(b){"$config"!=b&&(b=f(b),(!b||b&&
!b._defined)&&a.push(b))});return a},getDependencies:function(){var a=this,b=[];m(a.dependencies,function(d){d="$config"==d?a.config||null:f(d).definition||null;b.push(d)});return b},define:function(){function b(b){d.definedCallback=void 0;d.definition=b;d.end=(new Date).getTime();d.timeToDefine=d.end-d.start;d._defining=!1;d._defined=!0;setTimeout(a,1)}var d=this;d.defineStartTime=d.defineStartTime||(new Date).getTime();if(!d._defining&&!d._defined&&d.dependencies)if(d._defining=!0,0<d.getUnresolvedDependencies().length)d._defining=
!1;else{var g=d.getDependencies(),c={isAsync:!1,async:function(){d.isAsync=!0;c.isAsync=d.isAsync;return function(a){b(a)}}};(function(){if(d.definedCallback){var a=d.definedCallback;a=a&&a.apply(c,g);c.isAsync||b(a)}else b(!0)})()}},fetch:function(){var a=this;a._fetching||a._fetched||(a.url?(a._fetching=!0,a.startFetchTime=(new Date).getTime(),y.loadModule(a.url,function(){a._fetching=!1;a.endFetchTime=(new Date).getTime();a.timeToFetch=a.endFetchTime-a.startFetchTime;a._fetched=!0;a.define()})):
k("Tried to fetch a module without a url - dependencies: "+a.dependencies+" definedCallback: "+(a.definedCallback?"exists":"null")+" config: "+a.config))}};b.prototype={defineQueue:[],interactiveScript:null,currentlyAddingScript:null,getInteractiveScript:function(){if(y.interactiveScript&&"interactive"==y.interactiveScript.readyState)return y.interactiveScript;for(var a=document.getElementsByTagName("head")[0].getElementsByTagName("script"),b,d=a.length-1;0<=d;d--){var g=this.getScriptDataUrl(a[d]);
a[d]&&"interactive"==a[d].readyState&&g&&(b=a[d])}return b},scriptUrlAttributeName:"data-extole-require-url",getScriptDataUrl:function(a){return a.getAttribute(this.scriptUrlAttributeName)},setScriptDataUrl:function(a,b){a.setAttribute(this.scriptUrlAttributeName,b)},attachOnLoad:function(a,b){function d(r){var h=a.readyState;if(g&&"interactive"==h)this.interactiveScript=a;else if("load"===r.type||c.test(h))g?a.detachEvent("onreadystatechange",d):a.removeEventListener("load",d,!1),b(r)}b=b||function(){};
var g=this.useInteractive,c="PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/;g?a.attachEvent("onreadystatechange",d):a.addEventListener("load",d,!1)},defineTimeout:null,addDefine:function(a){if(a.url)a.url=h(a.url);else{var b=this.currentlyAddingScript||this.getInteractiveScript();this.useInteractive&&b&&(b=this.getScriptDataUrl(b),a.url=b,this.interactiveScript=null)}a.dependencies=l(a.dependencies,h);this.useInteractive&&!a.url&&k("defines should not be missing a url in ie.");
this.defineQueue.push(a);this.defineTimeout&&clearTimeout(this.defineTimeout);var d=this;this.defineTimeout=setTimeout(function(){d.intakeDefines()},1)},intakeTimeout:null,intakeDefines:function(){for(var b=[],d;d=this.defineQueue.shift();){var c=[];m(d.dependencies,function(a){a&&c.push(a)});d.url&&f(d.url);d.url||b.push("deps "+d.dependencies);m(c,function(a){g(a)});g(d.url,c,d.definedCallback,d.config,d.isRequire)}this.intakeTimeout&&clearTimeout(this.intakeTimeout);this.intakeTimeout=setTimeout(a,
1)},loadModule:function(a,b){var d=document.createElement("script");d.async=!0;d.crossOrigin="anonymous";this.setScriptDataUrl(d,a);var g=this;this.attachOnLoad(d,function(){clearTimeout(c);if(!g.useInteractive){for(var d,r=g.defineQueue.length-1;0<=r;r--)g.defineQueue[r].url||(d&&k("Multiple anonymous modules loaded in one script - "+a),d=g.defineQueue[r]);d&&(d.url=a)}g.intakeDefines();b&&b(null)});d.src=a;var c=setTimeout(function(){extole.log("warn","[REQUIRE] Module did not load within 2000ms: ",
{moduleUrl:a})},2E3);this.currentlyAddingScript=d;var r=document.getElementsByTagName("head")[0]||document.head;r?r.appendChild(d):extole.log("warn","[REQUIRE] <head> element not found on trying to load "+a,void 0);this.currentlyAddingScript=void 0}};var y=new b;d.getModule=function(a){return f(a)};var u=0;extole.define=d;extole.require=function(a,b){y.addDefine({url:r(),dependencies:a,definedCallback:b,isRequire:!0})};extole.define("extole-require",[],function(){return{resolveUrl:h}});setTimeout(function(){var a=
!1,b=[];m(x,function(d){d._defined||(a=!0);b.push({defineStartTime:d.defineStartTime,dependencies:d.dependencies,end:d.end,start:d.start,isRequire:d.isRequire,timeToDefine:d.timeToDefine,url:d.url,_defined:d._defined,_defining:d._defining,_fetched:d._fetched})});a&&extole.DUMP_REQUIRE_MODULES_ON_ERROR&&extole.log("error","After 7000ms there are unresolved extole-require modules.  ###"+JSON.stringify(b)+"###")},7E3)}();(function(){})();
extole.define("extole-uri-parser",["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/collection.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/uri.js"],function(f,k){var m=/^extole_(?!zone)/,l=/^extole_zone_/;return new function(){function e(c){var b={};c=c||h;f.each(c,function(a,g){m.test(g)&&(g=g.replace(m,""),b[g]=a)});return b}function n(){var c,b,a={};this.withName=function(a){c=a;return this};this.withElementId=function(a){b=
a;return this};this.withData=function(b,d){a[b]=d;return this};this.build=function(){var g={};c&&(g.name=c);b&&(g.elementId=b);a&&(g.data=a);return g}}var h=k.deserialize(location.search);this.parseUriZoneDefinition=function(c){var b=new n,a;c=c||h;var g=e(c);f.each(g,function(a,g){b.withData(g,a)});f.each(c,function(d,g){l.test(g)&&(g=g.replace(l,""),"name"===g?(a=!0,b.withName(d)):"element_id"===g?b.withElementId(d):b.withData(g,d))});return a?b.build():null};this.parseGlobalZoneParameters=e}});
(function(f,k,m,l,e){f[k]=f[k]||{};for(f[k].q=f[k].q||[];e<l.length;)m(l[e++],f[k])})(window,"extole",function(f,k){k[f]=k[f]||function(){k.q.push([f,arguments])}},["createZone","log"],0);
(function(){var f=[{name:"Branded Program Domain",programDomain:"share.skillshare.com",sitePatterns:["share.skillshare.com","skillshare.com","*.skillshare.com"],siteRegexPatterns:["share\\.skillshare\\.com\\.?$","skillshare\\.com\\.?$",".*\\.skillshare\\.com\\.?$"]}];extole.CORE_ROOT="https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57";extole.CORE_CONFIG={backendTargetingEnabled:!0,isZonePostEnabled:!0,isCookieConsentEnabled:!1,isJsCreativeRespondsWithHtmlEnabled:!1,isGlobalZoneParametersEnabled:!0,
isAccessTokenIncludedInResponseEnabled:!0,cookieConsentPolicy:"COOKIE_CONSENT_OR_SESSION_COOKIE",zonePostEnabled:!0,cookieConsentEnabled:!1};extole.CLIENT_ID="872040414";extole.BUILD_DATE="1687195944684";extole.VERSION="6.0";extole.IS_DEBUG_ENABLED=extole.debug||/[?&]extole_debug=true(&|$)/.test(location.search);extole.PROGRAM=function(){function k(b,a){b=Error.call(this,b);this.name="ExtoleError";this.message=b.message;this.stack=b.stack;this.code=a}function m(b,a){if(b.length)for(var g=0;g<b.length;g++)a(b[g],
g);else for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&a(b[g],g)}function l(b,a){var g=[];m(b,function(b){(b=a(b))&&(g[g.length]=b)});return g}function e(b,a){a=a||[];var g=!1;m(a,function(a){(new RegExp(a)).test(b)&&(g=!0)});return g}function n(){extole.require(["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/uri.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/ajax.js"],function(b,a){var g=extole.CORE_ROOT;b=g.replace(/(https?:\/\/[a-z-\.]+)(\/.*)/,
"$1")+"/_extole_core.gif"+b.serialize({core_root:g,referer:window.location.hostname});a({url:b})})}k.prototype=Error();k.prototype.constructor=k;var h=function(b){var a=window.location.hostname;return l(b,function(b){if(e(a,b.siteRegexPatterns))return b})}(f),c=h[0];if(!c)throw n(),new k("No program domain is configured for hostname: "+window.location.hostname+" unable to use Extole API","site_configuration_error");1<h.length&&extole.log("warn","Multiple programs matched hostname: "+window.location.hostname+
" programs: "+JSON.stringify(h));return c}();extole.require(["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/uri.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js","create-zone-executor"],function(k,f,l){function e(){function b(b){var d=b[0];"function"===typeof a[d]?(a[d].apply(null,b[1]),extole.q.history.push({name:b[0],args:b[1],timestamp:Date.now(),stack:Error().stack})):f.warn("Unable to execute method: "+d+", it is not implemented.")}
var a={log:function(){var a=Array.prototype.slice.call(arguments),b=a[0];"function"===typeof f[b]&&f[b].apply(null,a.slice(1))},createZone:l.initiateExecution};for(extole.q.history=[];extole.q.length;)b(extole.q.shift());extole.q.push=b}function n(){extole.require(["extole-uri-parser"],function(b){var a=k.deserialize(location.search);(b=b.parseUriZoneDefinition(a))&&extole.createZone(b)})}function h(){if("function"===typeof window.onerror)var b=window.onerror;window.onerror=function(a,g,d,c,h){if(b)try{b(a,
g,d,c,h)}catch(p){}g=g||window.location.href||"no_source_or_location.href";h=h&&h.stack?h.stack:"no_error.stack";var r=[],e=JSON.stringify({MESSAGE:a,SOURCE:g,LINE_NUMBER:d,COLUMN_NUMBER:c,STACK_TRACE:h},function(a,b){if(null!==b&&"object"===typeof b){if(0<=r.indexOf(b))return;r.push(b)}return b});d=extole.PROGRAM.programDomain.split(".").join("\\.");d=new RegExp("^(http|https):\\/\\/("+d+"|(([A-Za-z0-9-]{1,}\\.){1,}|)(xtlo\\.net|extole(\\.com|\\.io)))(?=(\\/|\\?|$))");((h+a).match(/extole/i)||d.test(g))&&
extole.require(["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js"],function(a){a.error("Unhandled exception",JSON.parse(e))})}}function c(){extole._bootstrapped=!0;h();e();n()}extole.bootstrap=c;extole._bootstrapped||c();if("undefined"!==typeof window.extoleAsyncInit)try{window.extoleAsyncInit()}catch(b){extole.require(["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js"],function(a){a.error("Error executing extended core javascript. Message : "+
b.message+" Stack: "+b.stack)})}})})();
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/ExtoleError.js",[],function(){function f(f,l,e,n){f=Error.call(this,f);this.name="ExtoleError";this.message=f.message||"no_message";this.stack=Error().stack;this.code=l||"extole_error";this.data=e||{};this.logLevel=0<=k.indexOf(n)?n:"error"}var k=["debug","info","warn","error"];f.prototype=Error();f.prototype.constructor=f;f.prototype.toString=function(){return this.name+" ["+this.logLevel+"]: message: "+
this.message+"; code: "+this.code+"; data: "+JSON.stringify(this.data,null,4)+"; stack trace: "+this.stack+";"};return f});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/collection.js",["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/ExtoleError.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/type.js"],function(f,k){function m(e,f){var h;if(e.length===Number(e.length))for(h=0;h<e.length;h++){var c=f(e[h],h);if(!1===c)return!1}else for(h in e)if(Object.prototype.hasOwnProperty.call(e,h)&&(c=f(e[h],h),
!1===c))return!1}function l(e){if(!e||"object"!==typeof e&&!k.isPlainFunction(e))e={};for(var f=1;f<arguments.length;f++)if(k.isPlainObject(arguments[f]))for(var h in arguments[f]){var c=arguments[f][h];c!==e&&void 0!==c&&(k.isPlainObject(c)&&k.isPlainObject(e[h])?c=l(e[h],c):k.isArray(c)&&k.isArray(e[h])&&e[h].concat&&(c=e[h].concat(c)),e[h]=c)}return e}m.BREAK=!1;return{each:m,map:function(e,l){function h(a,c){b=[];m(a,function(a,g){b.push(c(a,g))})}function c(a,c){b={};m(a,function(a,g){b[g]=c(a,
g)})}var b;if(k.isArray(e))h(e,l);else if(k.isPlainObject(e))c(e,l);else throw new f(e+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return b},filter:function(e,l){function h(a,c){b=[];m(a,function(a,g){c(a,g)&&b.push(a)})}function c(a,c){b={};m(a,function(a,g){c(a,g)&&(b[g]=a)})}var b;if(k.isArray(e))h(e,l);else if(k.isPlainObject(e))c(e,l);else throw new f(e+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return b},merge:l,clone:function(e){return JSON.parse(JSON.stringify(e))},
flatten:function(e){function f(c,b){if(k.isPlainObject(c))m(c,function(a,d){var c=b.slice();c.push(d);f(a,c)});else{var a=b.join(".");h[a]=c}}if(!k.isPlainObject(e))return e;var h={};f(e,[]);return h},find:function(e,f){var h;m(e,function(c,b){if(f(c,b))return h=c,m.BREAK});return h},reverse:function(e){var f=[];if(!e||e.length!==Number(e.length))return e;for(var h=e.length-1;0<=h;h--)f.push(e[h]);return f},nashornToJs:function(e){if(k.isPlainJs(e)||!e)return e;if(k.isJavaMap(e)){var f={};for(var h in e)f[h]=
e[h]}else if(k.isNumber(e.length))f=[],m(e,function(c,b){f[b]=c});else return e;return f},intersection:function(e,f){var h=[];m(e,function(c){0>f.indexOf(c)||0<=h.indexOf(c)||h.push(c)});return h},difference:function(e,f){var h=[];m(e,function(c){0<=f.indexOf(c)||0<=h.indexOf(c)||h.push(c)});return h}}});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/cookie.js",["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js"],function(f){function k(c){try{return decodeURIComponent(c.replace(e," "))}catch(b){return f.info("** cookie.decode ** Cookie error for: "+c,{error:b,message:b.message,stack:b.stack,cookiePart:c}),""}}function m(c){c=k(c);return 0===c.indexOf('"')?c.slice(1,-1).replace(n,'"').replace(h,"\\"):c}function l(c){if(!c||
!c.toUTCString){var b=new Date;b.setDate(b.getDate()+("number"===typeof c?c:0));return b}return c}var e=/\+/g,n=/\\"/g,h=/\\\\/g;return function(c,b,a){if(void 0!==b)return a=a||{},document.cookie=[encodeURIComponent(c),"=",encodeURIComponent(b),a.expires?"; expires="+l(a.expires).toUTCString():"",a.path?"; path="+a.path:"",a.domain?"; domain="+a.domain:"",a.samesite?"; samesite="+a.samesite:"","; secure"].join("");a:{b=document.cookie?document.cookie.split("; "):[];a=c?null:{};for(var g=0,d=b.length;g<
d;g++){var h=b[g].split("="),e=k(h[0]);if(!c)a[e]=m(h[1]);else if(c===e){c=m(h[1]);break a}}c=a}return c}});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/device-type.js",[],function(){function f(f){return k.test(f)}var k=/Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|Dolphin|Fennec|(hpw|web)OS|Zune|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Silk-Accelerated|Skyfire|NetFront/i,m=/WebView|\swv|(iPhone|iPod|iPad)(?!.*Safari)|Android.*(Version\/\d+\.\d+\s)|Linux; U; Android/i;return{isMobile:f,isDesktop:function(l){return!f(l)},isWebview:function(f){return m.test(f)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/dom.js",["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js"],function(f){function k(a,b){return(b||document).querySelectorAll(a)}function m(a,b){return k(a,b)[0]}function l(a,g){function d(){clearTimeout(x);g(e);n.removeListener(e,"load",d)}g=g||function(){};if(b[a]||!a)return g(b[a]),b[a]||null;b[a]=document.createElement("link");var e=b[a];h.setAttribute(e,"rel",
"stylesheet");h.setAttribute(e,"href",a);c.append(m("head"),e);n.addListener(e,"load",d);var x=setTimeout(function(){f.warn("Load timeout reached for stylesheet: ",{url:a});d()},5E3);return e}var e={each:function(a,b){var d;if(a.length===Number(a.length))for(d=0;d<a.length;d++){var c=b(a[d],d);if(!1===c)return!1}else for(d in a)if(Object.prototype.hasOwnProperty.call(a,d)&&(c=b(a[d],d),!1===c))return!1},extend:function(){var a,b,d=arguments[0]||{},c=1,h=arguments.length,e=!1,f=this.extend;"boolean"===
typeof d&&(e=d,d=arguments[1]||{},c=2);for("object"===typeof d||this.isFunction(d)||(d={});c<h;c++){var k=arguments[c];if(null!==k)for(a in k){var l=d[a];var q=k[a];d!==q&&(e&&q&&(this.isPlainObject(q)||(b=this.isArray(q)))?(b?(b=!1,l=l&&this.isArray(l)?l:[]):l=l&&this.isPlainObject(l)?l:{},d[a]=f(e,l,q)):void 0!==q&&(d[a]=q))}}return d},isFunction:function(a){return a&&"function"===typeof a&&a.call&&a.apply},isPlainObject:function(a){if("[object Object]"!==String(a)||a.nodeType||a.window&&a.window==
a)return!1;try{if(a.constructor&&!Object.prototype.hasOwnProperty.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(g){return!1}return!0},isArray:function(a){return a instanceof Array}};e.each.BREAK=!1;var n=function(){function a(a,b,d){for(var c=[],g=0;g<h.length;g++){var e=h[g];e.element==a&&e.eventType==b&&e.listener==d&&c.push({index:g,eventListener:e})}return c}function b(a){for(var b=[],d=0;d<h.length;d++){var c=h[d];c.element===a&&b.push(c)}return b}function d(a){this.originalEvent=
a;this.type=a.type;this.keyCode=a.keyCode;this.target=a.srcElement?a.srcElement:a.target}function c(b,d,c){c=a(b,d,c);0>=c.length?f.info("events.remove - Couldn't find exiting event listener for type \""+d+'" listener on element '+b):e.each(c,function(a){var c=a.index;a=a.eventListener;b.removeEventListener?b.removeEventListener(d,a.listenerWrapper,!1):b.detachEvent("on"+d,a.listenerWrapper);h.splice(c,1)})}var h=[];d.prototype={preventDefault:function(){var a=this.originalEvent;a.preventDefault?
a.preventDefault():a.returnValue=!1},stopPropagation:function(){var a=this.originalEvent;a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0}};return{addListener:function(b,c,g){function e(a){r&&(a=window.event);return g.call(b,new d(a))}if(0<a(b,c,g).length)f.warn("events.add - Listener already exists for event "+c+" on element "+b);else{var r=!b.addEventListener;h.push({element:b,eventType:c,listener:g,listenerWrapper:e});b.addEventListener?b.addEventListener(c,e,!1):b.attachEvent("on"+c,e)}},
triggerEvent:function(a,b,d){var c=document.createEvent("Event");d=e.extend({},d);var g=!1===!d.bubbles,h=!0===d.cancelable;delete d.bubbles;delete d.cancelable;c.initEvent(b,g,h);e.extend(c,d);a.dispatchEvent(c)},removeListener:c,clearListeners:function(a){a=b(a);e.each(a,function(a){c(a.element,a.eventType,a.listener)})}}}(),h=function(){function a(a){a=a.className;var b={};if(!a)return b;e.each(a.split(" "),function(a){b[a]=1});return b}function b(a){var b="";e.each(a,function(a,d){b+=" "+d});
return b.slice(1)}return{setAttribute:function(a,b,c){a.setAttribute(b,c);a[b]=c},getAttribute:function(a,b){return a.getAttribute(b)},removeAttribute:function(a,b){return a.removeAttribute(b)},addClass:function(d,c){var g=a(d);g[c]||(g[c]=1,d.className=b(g))},removeClass:function(d,c){var g=a(d);delete g[c];d.className=b(g)},getClassNames:function(a){return a.className.split(" ")}}}(),c=function(){function a(a){var b=document.createDocumentFragment(),d=document.createElement("div");d.innerHTML=a;
e.each(d.childNodes,function(a){1==a.nodeType&&b.appendChild(a)});return b}function b(a){var b;e.each(a.childNodes,function(a){if(!b&&1==a.nodeType)return b=a,e.each.BREAK});return b}return{prepend:function(d,c){var g=b(d),h=c;"string"===typeof c&&(h=a(c));g?d.insertBefore(h,g):d.appendChild(h)},append:function(b,c){var d=c;"string"===typeof c&&(d=a(c));b.appendChild(d)}}}(),b={};return{addEventListener:n.addListener,removeEventListener:n.removeListener,triggerEvent:n.triggerEvent,clearEventListeners:n.clearListeners,
getAttribute:h.getAttribute,setAttribute:h.setAttribute,removeAttribute:h.removeAttribute,addClass:h.addClass,removeClass:h.removeClass,getClassNames:h.getClassNames,prepend:c.prepend,append:c.append,query:k,queryFirst:m,isVisible:function(a,b){return!!(m(a,b)||{}).offsetParent},injectStylesheet:l,injectStylesheets:function(a,b){function d(a){--c||b(g)}b=b||function(){};if(0===a.length)b();else{var c=0,g=[];e.each(a,function(a){c++;setTimeout(function(){g.push(l(a,d))},1)})}},scrollIntoViewIfNeeded:function(a,
b){function c(a,b){return{start:a,length:b,end:a+b}}function g(a,c){return!1===b||c.start<a.end&&a.start<c.end?Math.min(a.start,Math.max(c.start,a.end-c.length)):(a.start+a.end-c.length)/2}function h(a,b){return{x:a,y:b,translate:function(c,d){return h(a+c,b+d)}}}function e(a,b){for(;a;)b=b.translate(a.offsetLeft,a.offsetTop),a=a.offsetParent;return b}var f=e(a,h(0,0)),l=h(a.offsetWidth,a.offsetHeight);a=a.parentNode;for(var k;a instanceof HTMLElement;)k=e(a,h(a.clientLeft,a.clientTop)),a.scrollLeft=
g(c(f.x-k.x,l.x),c(a.scrollLeft,a.clientWidth)),a.scrollTop=g(c(f.y-k.y,l.y),c(a.scrollTop,a.clientHeight)),f=f.translate(-a.scrollLeft,-a.scrollTop),a=a.parentNode}}});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/event-bus.js",[],function(){function f(){function f(h,c,b,a){if(!b)return!0;if("object"===typeof b){for(var g in b)h[c].apply(h,[g,b[g]].concat(a));return!1}if(n.test(b)){b=b.split(n);g=0;for(var d=b.length;g<d;g++)h[c].apply(h,[b[g]].concat(a));return!1}return!0}function e(h,c){var b,a=-1,g=h.length,d=c[0],e=c[1],f=c[2];switch(c.length){case 0:for(;++a<g;)(b=h[a]).callback.call(b.ctx);break;case 1:for(;++a<
g;)(b=h[a]).callback.call(b.ctx,d);break;case 2:for(;++a<g;)(b=h[a]).callback.call(b.ctx,d,e);break;case 3:for(;++a<g;)(b=h[a]).callback.call(b.ctx,d,e,f);break;default:for(;++a<g;)(b=h[a]).callback.apply(b.ctx,c)}}this._events={};var n=/\s+/;this.on=function(h,c,b){if(!f(this,"on",h,[c,b])||!c)return this;this._events||(this._events={});(this._events[h]||(this._events[h]=[])).push({callback:c,context:b,ctx:b||this});return this};this.off=function(h,c,b){var a,g,d;if(!this._events||!f(this,"off",
h,[c,b]))return this;if(!h&&!c&&!b)return this._events=void 0,this;var e=h?[h]:m.keys(this._events);var l=0;for(g=e.length;l<g;l++)if(h=e[l],a=this._events[h]){var k=[];this._events[h]=k;if(c||b){var n=0;for(d=a.length;n<d;n++){var p=a[n];(c&&c!==p.callback&&c!==p.callback._callback||b&&b!==p.context)&&k.push(p)}}k.length||delete this._events[h]}return this};this.once=function(h,c,b){function a(){var d=k.call(arguments);g.off(h,a,b);c.apply(this,d)}var g=this;this.on(h,a,b);return this};this.trigger=
function(h){if(!this._events)return this;var c=k.call(arguments,1);if(!f(this,"trigger",h,c))return this;var b=this._events[h],a=this._events.all;b&&e(b,c);a&&e(a,arguments);return this}}var k=Array.prototype.slice,m={isPlainObject:function(f){if("[object Object]"!==String(f)||f.nodeType||f.window&&f.window==f)return!1;try{if(f.constructor&&!Object.prototype.hasOwnProperty.call(f.constructor.prototype,"isPrototypeOf"))return!1}catch(e){return!1}return!0},keys:function(f){if(!this.isPlainObject(f))return[];
var e=[],k;for(k in f)Object.prototype.hasOwnProperty.call(f,k)&&e.push(k);return e},_idCounter:0,uniqueId:function(f){var e=String(++this._idCounter);return f?f+e:e}};return{create:function(){return new f}}});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js",[],function(){function f(a,b,c){e||(e=b.getGlobalServices().getJsLoggingService());e[a](c)}function k(d,e,f){var k=String(extole.CORE_ROOT).match(/coreAssetsVersion=(\d+)/);f=f||{};f.pageId=h;f.referer=c;f.coreAssetsVersion=k&&k[1];try{var r=[e||"no message","START_JSON",JSON.stringify(f),"END_JSON"].join(" ")}catch(p){l("Failed to stringify log's json data",{exception:p});return}if(!extole.LOG_EXCLUDE_REGEX||
!r.match(extole.LOG_EXCLUDE_REGEX)){g[r]=++g[r]||1;if(b[d]>=b[extole.LOG_LEVEL_CONSOLE]&&(e=d+" "+r,window.console))if(window.console[d.toLowerCase()])window.console[d.toLowerCase()](e);else window.console.log(e);b[d]>=b[extole.LOG_LEVEL_REMOTE]&&(e=g[r],a[e]&&m(d,r+(1<e?" log count: "+e:"")))}}function m(a,b){extole.require(["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/api.js"],function(c){c.post("/api/v4/debug/logs",{level:a,message:b},null,{headers:{"Content-Type":"application/x-www-form-urlencoded"}})})}
function l(a,b){k("ERROR",a,b)}var e;if("undefined"===typeof window)return{debug:function(a,b){f("debug",a,b)},info:function(a,b){f("info",a,b)},warn:function(a,b){f("warn",a,b)},error:function(a,b){f("error",a,b)},LOGGING_ENDPOINT:"/api/v4/debug/logs"};var n=extole.IS_DEBUG_ENABLED?"DEBUG":"OFF",h=String((new Date).getTime()),c=window.location.href,b={DEBUG:0,INFO:1,WARN:2,ERROR:3,OFF:4},a={1:!0,3:!0,10:!0,30:!0,100:!0,250:!0,500:!0,1E3:!0};extole.LOG_EXCLUDE_REGEX=extole.LOG_EXCLUDE_REGEX||void 0;
extole.LOG_LEVEL_CONSOLE=extole.LOG_LEVEL_CONSOLE||n;extole.LOG_LEVEL_REMOTE=extole.LOG_LEVEL_REMOTE||"WARN";var g={};return{debug:function(a,b){k("DEBUG",a,b)},info:function(a,b){k("INFO",a,b)},warn:function(a,b){k("WARN",a,b)},error:l,LOGGING_ENDPOINT:"/api/v4/debug/logs"}});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/Timer.js",[],function(){return function(){var f=this,k;this.start=function(){if(k)throw Error("Timer.start has already been called");k=new Date;return f};this.getElapsedTime=function(){if(!k)throw Error("Timer has not been started");return new Date-k}}});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/type.js",[],function(){function f(f,e){return function(l){return k(f,l,e)}}function k(f,e,k){k=k||{};f=Object.prototype.toString.call(e)==="[object "+f+"]";e=e&&k.construct?e.constructor===k.construct:!0;return(k.negate?!f:f)&&e}var m=/\[object (Function|Array|String|Boolean|Number|Undefined|Null)\]/;return{isPlainJs:function(f){return this.isPlainObject(f)||m.test(Object.prototype.toString.call(f))},isJavaMap:function(f){return"undefined"!==
typeof Java&&Java.type?f instanceof Java.type("java.util.Map"):!1},isPlainObject:f("Object",{construct:Object}),isPlainFunction:f("Function"),isArray:f("Array"),isString:f("String"),isBoolean:f("Boolean"),isNumber:f("Number"),isUndefined:f("Undefined"),isDefined:f("Undefined",{negate:!0}),isNull:f("Null"),test:k}});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/uri.js",["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/collection.js"],function(f){function k(c){var b={};(function r(c,d){for(var g in c){var e=c[g],f=(d?d+".":"")+g;"[object Object]"===Object.prototype.toString.call(e)?r(e,f):l(f)&&(b[f]=e)}})(c);return b}function m(c){try{return decodeURIComponent(c)}catch(b){return c}}function l(c){return"__proto__"!==c&&"prototype"!==
c&&"constructor"!==c}function e(c,b,a){b=(b||[]).concat("object"===typeof extole&&extole.PROGRAM?extole.PROGRAM.siteRegexPatterns:[]);a=n(a||location.href);c=n(c);return(/^https?:\/\//.test(c)?f.find(b,function(a){var b=h.exec(c);return(new RegExp(a)).test(b&&b[1])}):1)?c:a}function n(c){return c.replace(/(j|%4A|%6A)(a|%41|%61)(v|%56|%76)(a|%41|%61)(s|%53|%73)(c|%43|%63)(r|%52|%72)(i|%49|%69)(p|%50|%70)(t|%54|%74)(:|%3A)/gi,"")}var h=/^https?:\/\/([^/:?#]+)/i;return{serialize:function(c){var b="",
a;for(a in c)b+="&"+encodeURIComponent(a)+"="+encodeURIComponent(String(c[a]));return b.replace(/^&/,"?")},deserialize:function(c){var b={};if(!c)return b;c=(c.match(/^\?/)?c.slice(1):c).split("&");for(var a=0;a<c.length;a++){var g=c[a].split("="),d=m(g[0]);g=m(g[1]);l(d)&&(b[d]=g)}return b},objectToDotNotation:k,dotNotationToObject:function(c){var b={};c=k(c);for(var a in c){for(var g=b,d=a.split("."),e=d.pop();d.length;){var f=d.shift();l(f)&&(g[f]=g[f]||{},g=g[f])}l(e)&&(g[e]=c[a])}return b},decodeComponent:m,
encodeComponent:function(c){return encodeURIComponent(c)},getSafeRedirectUrl:e,executeSafeRedirect:function(c,b,a){window.location.href=e(c,b,a)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/ajax.js",["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/collection.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/uri.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/type.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js"],function(f,k,m,l){function e(b,
a){function c(){4!==b.readyState||A||(A=!0,String(b.status||200).match(/^[23]/)?"function"===typeof z?z.call(b,b.responseText,b):l.warn("'complete' callback must be a function."):C.call(b,b.statusText,b.status),h())}function d(a){A||(A=!0,l.error("Error with url "+w+"= "+n.join(","),e(a)),C.call(b,b.statusText,b.status))}function e(c){return{eventType:c&&c.type||null,options:a,readyState:b.readyState,response:b.response,responseText:b.responseText,responseType:b.responseType,responseURL:b.responseURL,
responseXML:b.responseXML,status:b.status,statusText:b.statusText,timeout:b.timeout,responseHeaders:b.getAllResponseHeaders()}}function h(a){0>w.indexOf(l.LOGGING_ENDPOINT)&&l.debug("ajax request complete",e(a))}var n=Array.prototype.slice.call(arguments),u=a.headers||{},p=a.xhrFields||{},w=a.url||"",q=a.data||"",t=(a.type||"get").toUpperCase(),z=a.complete||function(){},C=a.error||function(){};m.isPlainObject(q)&&("GET"===t?(w+=k.serialize(q),q=null):q=JSON.stringify(q));b.open(t,w,!0);f.merge(b,
p);f.each(u,function(a,c){try{b.setRequestHeader(c,a)}catch(E){l.error("AJAX ERROR: Couldn't set request header "+c+" to "+a)}});var A=!1;b.onload=c;b.onreadystatechange=c;b.onerror=d;b.ontimeout=d;b.onabort=h;b.send(q)}function n(b){f.each(b,function(a,c){"content-type"===c.toLowerCase()&&delete b[c]})}function h(b){b=b||{};var a=!1;for(var g=0;g<c.length;g++){try{a=c[g]()}catch(d){continue}break}e(a,b);return a}var c=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},
function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];h.convertToFormUrlEncoded=function(b,a){function c(a){var b={};f.each(a,function(a,d){d=0<=d.indexOf(".")?'"'+d+'"':d;m.isPlainObject(a)&&(a=c(a));b[d]=a});return b}var d=[];n(b);b["content-type"]="application/x-www-form-urlencoded";a=c(a);a=f.flatten(a);f.each(b,function(a,c){"content-type"!==c.toLowerCase()&&(d.push("::headers."+c+"="+a),delete b[c])});f.each(a,function(a,b){m.isUndefined(a)||
d.push(encodeURIComponent(b)+"="+(m.isNull(a)?"":encodeURIComponent(a)))});return d.join("&")};h.convertToMultipartFormData=function(b,a){var c=new FormData;f.each(a,function(a,b){c.append(b,a)});n(b);return c};return h});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/program.js",[],function(){return{getName:function(){return extole.PROGRAM.name},getProgramDomain:function(){return extole.PROGRAM.programDomain},getSitePatterns:function(){return extole.PROGRAM.sitePatterns},getSiteRegexPatterns:function(){return extole.PROGRAM.siteRegexPatterns},getProtocol:function(){return"https://"}}});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/token-store.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/ExtoleError.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/collection.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/event-bus.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/cookie.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/ajax.js".split(" "),
function(f,k,m,l,e,n){function h(){function d(){v[a.MEMORY]=v[a.MEMORY]||new w;v[a.COOKIE]=v[a.COOKIE]||new q;v[a.LOCAL_STORAGE]=v[a.LOCAL_STORAGE]||new t;extole.COOKIES_DISABLED&&(v[a.COOKIE].remove(),delete v[a.COOKIE]);extole.LOCAL_STORAGE_ALWAYS_ENABLED||extole.LOCAL_STORAGE_ENABLED_WHEN_CONSENTED||extole.LOCAL_STORAGE_ENABLED_WHEN_UNCONSENTED||(v[a.LOCAL_STORAGE].remove(),delete v[a.LOCAL_STORAGE])}function h(a){function b(d,e){c+=1;d?5>c?x(b):(d="Failed to fetch access token after 5 attempts. Last Error: "+
d.message,m.error(d),a(Error(d))):a(null,e)}var c=0;x(b)}function x(a){y("POST","/api/v5/token",null,function(b,c){a(b,c)})}function y(a,b,c,d){function e(a,b){try{var c=JSON.parse(a)}catch(H){b(H);return}b(null,c)}c=c||u();var g="https://"+extole.PROGRAM.programDomain+b+(c?"?access_token="+c:"");n({url:g,type:a,headers:{"content-type":"application/json"},complete:function(a){e(a,d)},error:function(c,h){var l=this,q="Api request to "+b+" failed: "+h+" "+c,m={method:a,url:g,statusText:c||null,http_status_code:h||
null};e(l.responseText,function(a,b){if(a){a="Failed to parse api error response as json";var c="json_parse_error";b=k.merge({response:l.responseText},m)}else a=b.message||q,c=b.code||"failed_api_request",b=k.merge({},b,m);d(new f(a,c,b))})}})}function u(){var a=B===b.YEAR?A():D();return(a=k.find(a,function(a){a=a.get();return!("string"!==typeof a||"undefined"===a||"null"===a||!a.length)}))?a.get():null}function p(a,c){var d=u();if(!a&&d)a=d;else if(!a&&!d)return;var e=d!==a;B=Object.prototype.hasOwnProperty.call(b,
c)&&c||(e||!B?z():B);C(B);k.each(B===b.YEAR?A():D(),function(b){b.set(a,B)});e&&E.trigger("change:access_token");d&&e&&m.debug("ACCESS_TOKEN_CHANGE - the access token changed from: "+d+", to: "+a)}function w(){var a={};this.get=function(){return a.extole_access_token};this.set=function(b){a.extole_access_token=b};this.remove=function(){delete a.extole_access_token}}function q(){this.get=function(){return e("extole_access_token")};this.set=function(a,b){e("extole_access_token",a,{expires:g[b.toUpperCase()],
path:"/",samesite:"strict"})};this.remove=function(){e("extole_access_token","",{expires:-1,path:"/"})}}function t(){var a;(function(){var b="test"+(new Date).getTime();try{localStorage.setItem(b,b),localStorage.removeItem(b)}catch(G){a=!1;return}a=!0})();this.get=function(){return a?localStorage.getItem("extole_access_token"):null};this.set=function(b){a&&localStorage.setItem("extole_access_token",b)};this.remove=function(){a&&localStorage.removeItem("extole_access_token")}}function z(){if(extole.CORE_CONFIG.isCookieConsentEnabled)switch(extole.CORE_CONFIG.cookieConsentPolicy){case c.COOKIE_CONSENT_OR_SESSION_COOKIE:return b.SESSION;
case c.COOKIE_CONSENT_OR_NO_COOKIE:return b.NO_COOKIE;default:return b.NO_COOKIE}return b.YEAR}function C(){var a=B===b.YEAR?A():D();k.each(v,function(b){0>a.indexOf(b)&&b.remove()})}function A(){var b=[a.MEMORY];Object.prototype.hasOwnProperty.call(v,a.COOKIE)&&b.push(a.COOKIE);(extole.LOCAL_STORAGE_ENABLED_WHEN_CONSENTED||extole.LOCAL_STORAGE_ALWAYS_ENABLED)&&b.push(a.LOCAL_STORAGE);return b.map(function(a){return v[a]})}function D(){var b=[a.MEMORY];extole.CORE_CONFIG.cookieConsentPolicy===c.COOKIE_CONSENT_OR_SESSION_COOKIE&&
Object.prototype.hasOwnProperty.call(v,a.COOKIE)&&b.push(a.COOKIE);(extole.LOCAL_STORAGE_ENABLED_WHEN_UNCONSENTED||extole.LOCAL_STORAGE_ALWAYS_ENABLED)&&b.push(a.LOCAL_STORAGE);return b.map(function(a){return v[a]})}var B,E=l.create(),v={};d();this.fetch=function(a){a=a||function(){};h(function(b,c){var d=c.access_token;d&&p(d);a(b,c,B)})};this.getTokenDetails=function(a){a=a||function(){};y("GET","/api/v5/token",u(),a)};this.get=u;this.set=p;this.remove=function(){B=z();k.each(v,function(a){a.remove()})};
this.setUnconsented=function(){B=z();p()};this.initializeStores=d;this.events=E}var c={COOKIE_CONSENT_DISABLED:"COOKIE_CONSENT_DISABLED",COOKIE_CONSENT_OR_SESSION_COOKIE:"COOKIE_CONSENT_OR_SESSION_COOKIE",COOKIE_CONSENT_OR_NO_COOKIE:"COOKIE_CONSENT_OR_NO_COOKIE"},b={NO_COOKIE:"NO_COOKIE",SESSION:"SESSION",YEAR:"YEAR"},a={MEMORY:"MEMORY",COOKIE:"COOKIE",LOCAL_STORAGE:"LOCAL_STORAGE"},g={YEAR:365,SESSION:null};extole.tokenStore=extole.tokenStore?extole.tokenStore:new h;return extole.tokenStore});
extole.define("https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/metric-registry.js",["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/program.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/ajax.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/token-store.js"],function(f,k,m){function l(e,c,b){b={metric_type:e,key:c,value:b};e={"Content-Type":"application/x-www-form-urlencoded",
"X-Extole-App":"javascript_sdk"};m.get()&&(e.Authorization="Bearer+"+m.get(),c=[f.getProtocol(),f.getProgramDomain(),"/api/v4/debug/metrics"].join(""),b=k.convertToFormUrlEncoded(e,b),k({url:c,type:"POST",headers:e,data:b,xhrFields:{withCredentials:!0}}))}function e(e){this.increment=function(c){l("COUNTER",e,c)}}function n(e){this.update=function(c){l("HISTOGRAM",e,c)}}return{histogram:function(e){return new n(e)},counter:function(f){return new e(f)}}});
extole.define("CreativeRenderContext",["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/uri.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/collection.js"],function(f,k){function m(e,f,c){this.getElement=function(){return c};this.getName=function(){return e};this.getData=function(){return f};this.getParameters=function(){return f}}function l(){this.getName=function(){return extole.PROGRAM.name};this.getProgramDomain=function(){return extole.PROGRAM.programDomain};
this.getSitePatterns=function(){return extole.PROGRAM.sitePatterns};this.getSiteRegexPatterns=function(){return extole.PROGRAM.siteRegexPatterns}}function e(){this.backendTargetingEnabled=function(){return!0};this.cookieConsentEnabled=function(){return extole.CORE_CONFIG.isCookieConsentEnabled}}return function(n,h,c,b){var a=new m(n,h,c),g=new l,d=new e;this.getZone=function(){return a};this.getProgram=function(){return g};this.getCreativeData=function(){var b=f.dotNotationToObject(f.deserialize(location.search)),
c=f.dotNotationToObject(a.getParameters());return k.merge(b.extole_creative,c.creative)};this.getCoreConfig=function(){return d};this.getLocale=function(){return b||null}}});
extole.define("find-element-by-id",["https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/metric-registry.js"],function(f,k){function m(f,e,k){function h(){if(e())k();else{f();var b=setTimeout;c||(c=10);var a=500<c?500:c*=1.1;b(h,a)}}var c;h()}return function(l,e){var n=(new Date).getTime(),h=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_NOT_FOUND||3E3,c=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_FOUND||
2E3,b=!1,a;m(function(){a=document.getElementById(l)},function(){var e=(new Date).getTime()-n,d=!!a;d&&e>=c?(k.histogram("zone_element_found_slow").update(e),f.warn("EXTOLE_ELEMENT_FOUND_SLOW: Scan duration: "+e+"ms, element id: "+l)):!extole.isFindElementBeforeZoneRequest&&!b&&e>=h&&(b=!0,k.histogram("zone_element_not_yet_found").update(e),f.warn("EXTOLE_ELEMENT_NOT_YET_FOUND: Scan duration: "+e+"ms, element id: "+l));return d},function(){e(a)})}});
extole.define("ensure-element",["find-element-by-id"],function(f){return function(k,m){k.element?m(k.element):k.element_id?f(k.element_id,m):m(document.body.appendChild(document.createElement("div")))}});
extole.define("pending-zone-service","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/device-type.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/dom.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/type.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/collection.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/metric-registry.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/token-store.js CreativeRenderContext ensure-element".split(" "),function(f,
k,m,l,e,n,h,c,b){function a(a,e){e=e||function(){};var f=a.name,l=d(a.data),m=Date.now();w(f);this.resolve=function(d,q,p,t){h.set(q,p);r(a)&&(q=g(f,"time_to_zone_response_ms"),p=Date.now()-m,n.histogram(q).update(p));b(a,function(b){a.element=b;r(a)&&x(a.element,function(){var a=g(f,"time_to_first_html_ms"),b=Date.now()-m;n.histogram(a).update(b)});k.clearEventListeners(a.element);b=new c(f,l,a.element,t);d(b);e(null,b.getZone())})}}function g(a,b){var c=document.getElementsByTagName("*").length;
c=2500<c?"xx_large":1500<c?"x_large":1E3<c?"large":500<c?"medium":"small";var d=f.isMobile((window.navigator||{}).userAgent)?"mobile":"desktop";return[a,d,c,b].join("_")}function d(a){a=e.merge({},a);delete a.campaign_id;delete a.extole_campaign_id;return a}function r(a){return u.test(a.name)||u.test((a.data||{}).redirect)?!0:!1}function x(a,b){var c=document.createElement("div");c.style.display="none";a.appendChild(c);y(c,b)}function y(a,b){if(window.MutationObserver){var c=new MutationObserver(function(d){e.each(d,
function(d){d.removedNodes&&e.each(d.removedNodes,function(d){d===a&&(b(),c.disconnect())})})});a.parentNode&&c.observe(a.parentNode,{childList:!0})}}var u=/_experience$/,p={},w=function(){var a={};return function(b){m.isUndefined(a[b])&&(a[b]=0);a[b]++;if(5===a[b]){b="duplicate_zone_requests : "+b;var c=e.filter(extole.q.history,function(a){return a.name&&"createZone"===a.name});c=e.map(c,function(a){delete (a.args[0]||{}).element;return a});l.warn(b,c)}}}();return{get:function(a){if(!p[a])throw Error("Pending zone does not exist for id: "+
a);return p[a]},create:function(){var b=Math.floor(1E9*Math.random()),c=0;return function(d,e){c++;var f=b+"."+c;p[f]=new a(d,e);return f}}()}});
extole.define("create-zone","extole-uri-parser https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/uri.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/collection.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/dom.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/program.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/token-store.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/ajax.js https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/ExtoleError.js pending-zone-service".split(" "),function(f,
k,m,l,e,n,h,c,b){function a(a){var b=document.createElement("script");l.setAttribute(b,"src",a);l.setAttribute(b,"async","");l.append(l.queryFirst("head")||l.queryFirst("body"),b);return b}return function(g,d,r){function x(){z&&(t.jwt=z);C&&(t.access_token=C);D&&(t.debug="true");t.extole_app="javascript_sdk";w=[A,"/zones/",g.name].join("");var b=a(w+k.serialize(t));b.onload=p;b.onerror=function(){u(new c("Zone script tag request failed","zone_tag_request_failure",null))}}function y(){var a={"Content-Type":"application/x-www-form-urlencoded",
Accept:"text/javascript","X-Extole-App":"javascript_sdk"};w=A+"/zones/"+g.name;z&&(a["X-Extole-Jwt"]=z,delete t.jwt);C&&(a.Authorization="Bearer+"+C);D&&(a["X-Extole-Debug"]="true");var b=h.convertToFormUrlEncoded(a,t);h({url:w,type:"POST",headers:a,data:b,complete:function(a,b){var d=/^text\/html(;|$)/,e=/^text\/plain(;|$)/;b=b.getResponseHeader("Content-Type");if(/^text\/javascript(;|$)/.test(b))var f=a;else d.test(b)?(d=document.createElement("div"),d.innerHTML=a,f=l.queryFirst("script",d).innerHTML):
e.test(b)&&!a?u(new c("Empty response","empty_response",null,"info")):u(new c("Received invalid content type: '"+b+"'","invalid_content_type",null,"warn"));if(f)try{(new Function(f))()}catch(F){u(new c("Error in zone script - MESSAGE: "+F.message+" STACK: "+F.stack,"zone_script_error"))}p()},error:function(a,b){try{var d=JSON.parse(this.responseText)}catch(G){d={status:b||null,statusText:a||null}}u(new c(d.message||"Ajax zone request failed",d.code||null,d))},xhrFields:{withCredentials:!0}})}function u(a){var b=
"Problem creating zone with "+(extole.CORE_CONFIG.isZonePostEnabled?"POST":"GET"),e=m.merge({originalMessage:a.message,zoneRequestUrl:w||null,zoneDefinition:g},a.data);d(new c(b,a.code||"zone_request_failed",e,a.logLevel||"error"));p()}function p(){"function"===typeof r&&setTimeout(r,500)}d=d||function(){};var w,q=k.deserialize(location.search),t=m.merge({},g.data||g.parameters),z=g.jwt||t.jwt||q.extole_jwt,C=n.get(),A=[e.getProtocol(),e.getProgramDomain()].join(""),D=t.debug&&"false"!==t.debug||
extole.IS_DEBUG_ENABLED;extole.isPassRefererInZoneData&&(t.referer=location.href);extole.CORE_CONFIG.isGlobalZoneParametersEnabled&&(q=f.parseGlobalZoneParameters(q),t=m.merge(t,q));if(extole.createZonePrehandler&&(q=extole.createZonePrehandler(g,t),!1===q)){u(new c("Zone request cancelled","zone_request_cancelled",null,"info"));return}g.element_id&&(t.element_id=g.element_id);g.data=t;t.zone_id=b.create(g,d);t=m.flatten(t);extole.CORE_CONFIG.isZonePostEnabled?y():x()}});
extole.define("create-zone-executor",["create-zone","ensure-element","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/logger.js","https://origin.xtlo.net/type=core:clientId=872040414:coreAssetsVersion=57/common/client/token-store.js"],function(f,k,m,l){function e(e,k,n){function p(a){if(a)r(a);else{g=!0;var b=Array.prototype.slice.call(arguments);(k||function(){}).apply(null,b);q()}}function r(b){function f(){setTimeout(function(){h(e,k,n)},1)}n+=1;if(5>n)if(c(b))g=
!1,l.remove(),f();else if("zone_tag_request_failure"!==b.code||extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled)if("invalid_content_type"===b.code)f();else m[b.logLevel||"error"](b.toString());else a.stop(),d(function(b,c){c?g=!0:!1===c&&(g=!1,l.remove());a.start();f()});else m[b.logLevel||"error"](b.toString()),m.warn("ERROR_WOULD_BE_PASSED_TO_CREATE_ZONE_CALLBACK")}var q;a.push(function(a){q=b(a);f(e,p,q);g&&q()})}function n(a){function b(){for(;c.length;)c.shift().apply(null,arguments)}
var c=[],d=!1;return function(e){c.push(e);d||(d=!0,a(function(){d=!1;b.apply(null,arguments)}))}}function h(a,b,c){function d(){var d=!!l.get(),f=!!a.element;!extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled&&!d||extole.isFindElementBeforeZoneRequest&&!f||e(a,b,c)}c=Number(c)||0;l.get()||extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled||r(d);extole.isFindElementBeforeZoneRequest&&k(a,function(b){a.element=b;d()});d()}function c(a){a=a||{};return a.data&&403===a.data.http_status_code&&
("invalid_access_token"===a.code||"expired_access_token"===a.code)}function b(a){var b=!1;return function(){var c=Array.prototype.slice.call(arguments);b||(b=!0,a.apply(null,c))}}var a=new function(){var a=0,b=[],c=this,d=!1;this.push=function(a){b.push(a);this.next()};this.next=function(){function e(){a--;c.next()}if(!d)for(;1>a&&b.length;)b.shift()(e),a++};this.start=function(){d=!1;this.next()};this.stop=function(){d=!0}},g=!1,d=n(function(a){l.getTokenDetails(function(b,d){b?c(b)?a(null,!1):a(b):
a(null,0<d.expires_in)})}),r=n(l.fetch);return{initiateExecution:h}});